// <auto-generated />
using FlexiLedger.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlexiLedger.Api.Migrations
{
    [DbContext(typeof(FlexiLedgerDbContext))]
    [Migration("20260630115620_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlexiLedger.Api.Models.Domain.FlexiNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("Carrier")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FlexiNumbers");
                });

            modelBuilder.Entity("FlexiLedger.Api.Models.Domain.FlexiRecharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Carrier")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneNumberId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RechargeAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("RechargeNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FlexiRecharges");
                });
#pragma warning restore 612, 618
        }
    }
}
