// <auto-generated />
using FlexiLedger.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlexiLedger.Api.Migrations
{
    [DbContext(typeof(FlexiLedgerDbContext))]
    [Migration("20260709211014_RechareModelUpdate")]
    partial class RechareModelUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlexiLedger.Api.Models.Domain.FlexiNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("Carrier")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FlexiNumbers");
                });

            modelBuilder.Entity("FlexiLedger.Api.Models.Domain.FlexiRecharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Carrier")
                        .HasColumnType("integer");

                    b.Property<int>("FlexiNumberId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RechargeAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("RechargeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlexiNumberId");

                    b.ToTable("FlexiRecharges");
                });

            modelBuilder.Entity("FlexiLedger.Api.Models.Domain.FlexiRecharge", b =>
                {
                    b.HasOne("FlexiLedger.Api.Models.Domain.FlexiNumber", "FlexiNumber")
                        .WithMany()
                        .HasForeignKey("FlexiNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlexiNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
